[package]
name = "zmypy"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
zuban_python.workspace = true
config_searcher.workspace = true
config.workspace = true

clap.workspace = true

[features]
zuban_debug = ["zuban_python/zuban_debug"]
