[workspace]

resolver = "2"
members = [
    "parsa",
    "parsa_python",
    "parsa_python_cst",
    "zuban_python",
    "scripts",
    "zmypy",
]

[workspace.package]
edition = "2021"
rust-version = "1.81"
homepage = "https://zubanls.com"
authors = ["Dave Halter <davidhalter88@gmail.com>"]
