[package]
name = "utils"
version = "0.0.2"
edition.workspace = true
rust-version.workspace = true
publish = false
homepage.workspace = true
authors.workspace = true

[dependencies]
fnv.workspace = true
dirs.workspace = true
