[package]
name = "parsa"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
lazy_static = "*"
fnv = "*"

[dev-dependencies]
regex = "*"
