[package]
name = "zuban_python"
version = "0.1.0"
authors = ["Dave Halter <davidhalter88@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parsa_python = { path = "../parsa_python" }
parsa = { path = "../parsa" }
