[package]
name = "scripts"
version = "0.0.0"
publish = false
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parsa_python.workspace = true
zuban_python.workspace = true
