name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
    all_tests:
      required: false
      default: false
      type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  cargo-fmt:
    name: "cargo fmt"
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
      - name: "Install Rust toolchain"
        run: rustup component add rustfmt
      - run: cargo fmt --all --check

  tests:
    uses: ./.github/workflows/tests.yml
    with:
      all_tests: ${{ inputs.all_tests || false }}
    secrets: inherit
