name: New Release

# We only want one release process running for each tag.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.11"
  DEPLOY_DIR: "deploy/pypi/zuban"

defaults:
  run:
    shell: bash
    working-directory: ${{ env.DEPLOY_DIR }}


on:
  tags:
    - 'v[0-9]*'
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - i686-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64
      - name: "Pre-Build"
        run: ./pre-maturin-build.sh
      - name: "Build Wheel"
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          working-directory: ${{ env.DEPLOY_DIR }}
          manylinux: auto
          args: --release --locked --out dist --ignore-rust-version
      - name: "Post-Build"
        run: ./pre-maturin-build.sh
      - name: "Test wheel"
        if: ${{ startsWith(matrix.target, 'x86_64') }}
        run: ./test-maturin-build.sh
      - name: "Publish wheel"
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        uses: PyO3/maturin-action@v1
        with:
          command: upload
          args: "--skip-existing dist/*"
